
-- 데이터 테이블

-- 메뉴 테이블 MENU
-- 메뉴 코드 (기본키) MENU_CODE
-- 메뉴명 MENU_NAME
-- 메뉴 경로 MENU_URI
-- 메뉴번호 (권한) 0 공통, 1 이용자, 2 관리자

-- 도서관소개 0
-- 자료찾기 0
-- 서비스 0
-- 열린마당 0
-- 나의도서관 1
-- 도서관관리 2


CREATE TABLE MENU (
    MENU_CODE VARCHAR2(50)
    , MENU_NAME VARCHAR2(100) NOT NULL UNIQUE
    , MENU_URI VARCHAR2(100) NOT NULL UNIQUE
    , MENU_AUTO NUMBER NOT NULL
    , CONSTRAINT MENU_PK PRIMARY KEY (MENU_CODE)
    );


-- 사이드 SIDE_MENU

-- 메뉴 코드 (기본키) SIDE_MENU_CODE
-- 메뉴명 SIDE_MENU_NAME
-- 메뉴 경로 SIDE_MENU_URI

CREATE TABLE SIDE_MENU (
    SIDE_MENU_CODE VARCHAR2(50)
    , SIDE_MENU_NAME VARCHAR2(100) NOT NULL UNIQUE
    , SIDE_MENU_URI VARCHAR2(100) NOT NULL UNIQUE
    , CONSTRAINT SIDE_MENU_FK FOREIGN KEY (MENU_CODE) REFERENCES MENU (MENU_CODE) ON DELETE CASCADE
    , CONSTRAINT SIDE_MENU_PK PRIMARY KEY (SIDE_MENU_CODE)
    );


-- 책 정보 테이블 BOOK

-- ISBN (UNIQUE)
-- 책코드 BOOK_CODE (기본키)
-- 청구기호 KDC 000 총류 100 ~~~~~ 앞자리따서 분류
-- 저자 WRITER
-- 표제 TITLE
-- 쪽수 PAGE
-- 크기 SIZE
-- 주제 KEYWORD
-- 출판사 PUBLISHER
-- 발행년 PUB_DATE
-- 표지이미지 IMG
-- 책 요약 SUMMARY
-- 책 소개 INTRO
-- 책 등록일 INPUT_DATE
-- 자료위치 AREA
-- 종합자료실1 종합자료실2 열람실 어린이실

CREATE TABLE BOOK (
    ISBN NUMBER
    , BOOK_CODE VARCHAR2(50)
    , KDC VARCHAR2(50)
    , WRITER VARCHAR2(100)
    , TITLE VARCHAR2(200)
    , PAGE NUMBER
    , SIZE VARCHAR2(50)
    , KEYWORD VARCHAR2(50)
    , PUBLISHER VARCHAR2(100)
    , PUB_DATE VARCHAR2(20)
    , IMG VARCHAR2(100)
    , SUMMARY VARCHAR2(200)
    , INTRO VARCHAR2(3000)
    , INPUT_DATE DATE DEFAULT SYSDATE
    , AREA VARCHAR2(100)
); 

-- 대여 테이블

-- 대여 코드 기본키
-- 대출자 BORROWER
-- 대출한책
-- 대출한날
-- 반납날 + 대출날 7일 이후

CREATE TABLE RENTAL (
    RENTAL_CODE VARCHAR2(50)
    , ID VARCHAR2(100)
    , BOOK_CODE VARCHAR2(50)
    , RENTAL_DATE DATE DEFAULT SYSDATE
    , RETURN_DATE DATE DEFAULT SYSDATE + 7
    , CONSTRAINT RENTAL_PK PRIMARY KEY (RENTAL_CODE)
    , CONSTRAINT RENTAL_ID_FK FOREIGN KEY (ID) REFERENCES USER (ID)
    , CONSTRAINT RENTAL_BOOK_FK FOREIGN KEY (BOOK_CODE) REFERENCES BOOK (BOOK_CODE)
    );


-- 예약 테이블

-- 예약 코드 기본키
-- 예약자 BORROWER
-- 예약한책

CREATE TABLE RESERVE (
    MENU_CODE VARCHAR2(50)
    , MENU_NAME VARCHAR2(100) NOT NULL UNIQUE
    , MENU_URI VARCHAR2(100) NOT NULL UNIQUE
    , MENU_AUTO NUMBER NOT NULL
    , CONSTRAINT RESERVE_PK PRIMARY KEY (ID)
    );

-- 이용자 테이블 USER

-- 필수사항
-- 아이디 ID
-- 비밀번호 PW
-- 이름 NAME
-- 주소 ADDR
-- 연락처 TELL
-- 관리자 여부 IS_ADMIN
-- 탈퇴여부 IS_DELETE

-- 선택사항
-- 성별 GENDER
-- 관심카테고리 FAVORITE

CREATE TABLE USER (
    ID VARCHAR2(100)
    , PW VARCHAR2(100) NOT NULL
    , NAME VARCHAR2(50) NOT NULL
    , ADDR VARCHAR2(200) NOT NULL
    , TELL VARCHAR2(100) NOT NULL
    , IS_ADMIN VARCHAR2(10) DEFAULT 'N'
    , IS_DELETE VARCHAR2(10) DEFAULT 'N'
    , GENDER VARCHAR2(10)
    , FAVORITE VARCHAR2(100)
    , CONSTRAINT USER_PK PRIMARY KEY (ID)
    );

-- 이미지 테이블 BOOK_IMG

-- 이미지 코드 IMG_CODE (기본키)
-- 실제 업로드 된 첨부파일명 ORIGIN_IMG_NAME
-- 첨부된 첨부파일 명 ATTACHED_IMG_NAME
-- 책코드 BOOK_CODE

CREATE TABLE BOOK_IMG (
    IMG_CODE VARCHAR2(100)
    , ORIGIN_IMG_NAME VARCHAR2(300)
    , ATTACHED_IMG_NAME VARCHAR2(300)
    , BOOK_CODE VARCHAR2(50)
    , IS_MAIN VARCHAR2(6)
    , CONSTRAINT IMG_PK PRIMARY KEY (IMG_CODE)
    , CONSTRAINT IMG_FK FOREIGN KEY (BOOK_CODE) REFERENCES BOOK (BOOK_CODE)
);











